ALTER TABLE public.sigem_documents
  ADD COLUMN IF NOT EXISTS nivel2 TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS nivel3 TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS dias_corridos_wf INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status_workflow TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS proposito_emissao TEXT DEFAULT '';