
CREATE TABLE public.permissoes_modulo (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  role TEXT NOT NULL,
  modulo TEXT NOT NULL,
  pode_ver BOOLEAN DEFAULT true,
  pode_editar BOOLEAN DEFAULT false,
  pode_criar BOOLEAN DEFAULT false,
  pode_excluir BOOLEAN DEFAULT false,
  pode_exportar BOOLEAN DEFAULT false,
  UNIQUE(role, modulo)
);

ALTER TABLE public.permissoes_modulo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "read_all" ON public.permissoes_modulo
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "admin_write" ON public.permissoes_modulo
  FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

INSERT INTO public.permissoes_modulo (role, modulo, pode_ver, pode_editar, pode_criar, pode_excluir, pode_exportar) VALUES
  ('admin_contrato', 'dashboard', true, true, true, true, true),
  ('admin_contrato', 'medicao', true, true, true, true, true),
  ('admin_contrato', 'previsao', true, true, true, true, true),
  ('admin_contrato', 'gitec', true, true, true, true, true),
  ('admin_contrato', 'documentos', true, true, true, true, true),
  ('admin_contrato', 'simulador', true, true, true, true, true),
  ('admin_contrato', 'boletim', true, true, true, true, true),
  ('admin_contrato', 'alertas', true, true, true, true, true),
  ('admin_contrato', 'cronograma', true, true, true, true, true),
  ('admin_contrato', 'bm', true, true, true, true, true),
  ('admin_contrato', 'cobertura', true, true, true, true, true),
  ('admin_contrato', 'equipes', true, true, true, true, true),
  ('admin_contrato', 'disciplinas', true, true, true, true, true),
  ('admin_contrato', 'etf', true, true, true, true, true),
  ('admin_contrato', 'tubulacao', true, true, true, true, true),
  ('admin_contrato', 'import', true, true, true, true, true),
  ('admin_contrato', 'config', true, true, true, true, true),
  ('gestor', 'dashboard', true, true, true, false, true),
  ('gestor', 'medicao', true, true, true, false, true),
  ('gestor', 'previsao', true, true, true, false, true),
  ('gestor', 'gitec', true, true, false, false, true),
  ('gestor', 'documentos', true, true, true, false, true),
  ('gestor', 'simulador', true, true, true, false, true),
  ('gestor', 'boletim', true, true, true, false, true),
  ('gestor', 'alertas', true, false, false, false, true),
  ('gestor', 'cronograma', true, true, false, false, true),
  ('gestor', 'bm', true, true, true, false, true),
  ('gestor', 'cobertura', true, false, false, false, true),
  ('gestor', 'equipes', true, true, true, false, false),
  ('gestor', 'disciplinas', true, false, false, false, true),
  ('gestor', 'etf', true, true, true, false, true),
  ('gestor', 'tubulacao', true, false, false, false, true),
  ('gestor', 'import', true, true, true, false, false),
  ('gestor', 'config', true, false, false, false, false),
  ('coordenador', 'dashboard', true, false, false, false, true),
  ('coordenador', 'medicao', true, false, false, false, true),
  ('coordenador', 'previsao', true, true, true, false, false),
  ('coordenador', 'gitec', true, false, false, false, false),
  ('coordenador', 'documentos', true, true, false, false, false),
  ('coordenador', 'simulador', true, true, true, false, false),
  ('coordenador', 'boletim', true, false, false, false, false),
  ('coordenador', 'alertas', true, false, false, false, false),
  ('coordenador', 'cronograma', true, false, false, false, false),
  ('coordenador', 'bm', true, false, false, false, false),
  ('coordenador', 'cobertura', true, false, false, false, false),
  ('coordenador', 'equipes', true, false, false, false, false),
  ('coordenador', 'disciplinas', true, false, false, false, false),
  ('coordenador', 'etf', true, true, true, false, true),
  ('coordenador', 'tubulacao', true, false, false, false, false),
  ('coordenador', 'import', false, false, false, false, false),
  ('coordenador', 'config', false, false, false, false, false),
  ('tecnico', 'dashboard', true, false, false, false, false),
  ('tecnico', 'medicao', true, false, false, false, false),
  ('tecnico', 'previsao', true, true, true, false, false),
  ('tecnico', 'gitec', true, false, false, false, false),
  ('tecnico', 'documentos', true, false, false, false, false),
  ('tecnico', 'simulador', true, false, false, false, false),
  ('tecnico', 'boletim', true, false, false, false, false),
  ('tecnico', 'alertas', true, false, false, false, false),
  ('tecnico', 'cronograma', true, false, false, false, false),
  ('tecnico', 'bm', true, false, false, false, false),
  ('tecnico', 'cobertura', true, false, false, false, false),
  ('tecnico', 'equipes', true, false, false, false, false),
  ('tecnico', 'disciplinas', true, false, false, false, false),
  ('tecnico', 'etf', true, true, true, false, false),
  ('tecnico', 'tubulacao', true, false, false, false, false),
  ('tecnico', 'import', false, false, false, false, false),
  ('tecnico', 'config', false, false, false, false, false),
  ('visualizador', 'dashboard', true, false, false, false, false),
  ('visualizador', 'medicao', true, false, false, false, false),
  ('visualizador', 'previsao', true, false, false, false, false),
  ('visualizador', 'gitec', true, false, false, false, false),
  ('visualizador', 'documentos', true, false, false, false, false),
  ('visualizador', 'simulador', true, false, false, false, false),
  ('visualizador', 'boletim', true, false, false, false, false),
  ('visualizador', 'alertas', true, false, false, false, false),
  ('visualizador', 'cronograma', true, false, false, false, false),
  ('visualizador', 'bm', true, false, false, false, false),
  ('visualizador', 'cobertura', true, false, false, false, false),
  ('visualizador', 'equipes', true, false, false, false, false),
  ('visualizador', 'disciplinas', true, false, false, false, false),
  ('visualizador', 'etf', true, false, false, false, false),
  ('visualizador', 'tubulacao', true, false, false, false, false),
  ('visualizador', 'import', false, false, false, false, false),
  ('visualizador', 'config', false, false, false, false, false);
